### ISSUE TITLE
Running against a new repo gives errror

### ISSUE THREAD

**Issue by patrickn** [lfaoro/gtag#3]
Running 'gtag list' against a new repo with no existing tags displays an error message.

macOS 10.14.6
git version 2.20.1

`~/my-new-repo> gtag list
ERROR: usage: git cat-file (-t [--allow-unknown-type] | -s [--allow-unknown-type] | -e | -p | <type> | --textconv | --filters) [--path=<path>] <object>
   or: git cat-file (--batch | --batch-check) [--follow-symlinks] [--textconv | --filters]

<type> can be one of: blob, tree, commit, tag
    -t                    show object type
    -s                    show object size
    -e                    exit with zero when there's no error
    -p                    pretty-print object's content
    --textconv            for blob objects, run textconv on object's content
    --filters             for blob objects, run filters on object's content
    --path <blob>         use a specific path for --textconv/--filters
    --allow-unknown-type  allow -s and -t to work with broken/corrupt objects
    --buffer              buffer --batch output
    --batch[=<format>]    show info and content of objects fed from the standard input
    --batch-check[=<format>]
                          show info about objects fed from the standard input
    --follow-symlinks     follow in-tree symlinks (used with --batch or --batch-check)
    --batch-all-objects   show all objects with --batch or --batch-check
    --unordered           do not order --batch-all-objects output

: exit status 129`

**Comment by lfaoro** [comment]
Hi @patrickn, thank you very much for letting me know about this; it's a very bad problem :)

I'll be working on it today, find a code fix and write some tests to avoid issues like this from happening again.

I'll message you when done, so you can try again.

**Comment by lfaoro** [comment]
The issue seems to be related to some tags not having any information, common with older repos -- probably older git version were not creating tagging metadata.

It's fixed with the next patch, now if there's no data the tool will simply display: `tag v1.0.0 has no data available` instead of the showing to the user the above error.

**Comment by lfaoro** [comment]
@patrickn -- when you have a minute, if you installed gtag with homebrew please input `brew upgrade gtag` otherwise, please rebuild with a `go install`.

Confirm if your issue is fixed by closing it

**Comment by lfaoro** [comment]
@patrickn I'm going to close this issue, if you still experience the problem, reopen it.
